@extends('layouts.app')

@section('container')

    <a href="{{ route("form.create") }}" role="button" class="btn create-btn" data-tooltip="true" data-tooltip-title="Buat form baru">
        <span>+</span>
        Buat Form Baru
    </a>

    <!-- Statistics -->
    <div class="stats-grid" role="grid" aria-label="Statistics grid" aria-orientation="horizontal" aria-live="polite">
        <div class="stat-card" role="gridcell" aria-colindex="1">
            <div class="stat-icon forms">📝</div>
            <div class="stat-number">12</div>
            <div class="stat-label">Total Forms</div>
        </div>
        <div class="stat-card" role="gridcell" aria-colindex="2">
            <div class="stat-icon responses">📊</div>
            <div class="stat-number">247</div>
            <div class="stat-label">Total Respon</div>
        </div>
        <div class="stat-card" role="gridcell" aria-colindex="3">
            <div class="stat-icon active">✅</div>
            <div class="stat-number">8</div>
            <div class="stat-label">Forms Aktif</div>
        </div>
        <div class="stat-card" role="gridcell" aria-colindex="4">
            <div class="stat-icon views">👁️</div>
            <div class="stat-number">1,435</div>
            <div class="stat-label">Total Views</div>
        </div>
    </div>

    <!-- Forms Section -->
    <div class="forms-section" role="region" aria-labelledby="forms-section-header" aria-describedby="forms-grid">
        <div class="section-header" id="forms-section-header">
            <h2 class="section-title">Forms Terbaru</h2>
            <select class="filter-dropdown" id="filter-forms" aria-label="Filter forms" aria-controls="formsGrid" aria-expanded="false">
                <option value="all">Semua Forms</option>
                <option value="active">Aktif</option>
                <option value="draft">Draft</option>
                <option value="closed">Ditutup</option>
            </select>
        </div>

        <div class="forms-grid" id="forms-grid" role="grid">
            <!-- Form cards will be generated by JavaScript -->
        </div>
    </div>

@endsection